config/routes.rb
Rails.application.routes.draw do
  get 'leagues/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/about', to: 'pages#about'
  #Routes for user
  resources :users, only: [:show, :edit, :update]

  #Routes for the team
  resources :teams, only: [:show, :new, :create] do
    resources :leagues, only: [:index]
    member do
      get 'finalize', as: :finalize
      patch 'switch', as: :switch
      patch 'retrieve', as: :retrieve
    end
  end

  #Route for transferring player
  resources :players, only: [:edit, :update] do
    get 'modal', to: "players#footballer", as: :modal
  end

  #Routes for footballers
  resources :footballers, only: [:index, :show] do
    get 'modal', to: "teams#footballer", as: :modal
  end

  #Routes for fixtures
  resources :fixtures, only: [:index, :show]

  #Routes for leagues
  resources :leagues, only: [:show]

  # Routes for sidekiq
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/league.rb
class League < ApplicationRecord
  has_many :team_entries

  validates :name, :fpl_league_id, presence: true
  validates :fpl_league_id, numericality: { only_integer: true }
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  def show
    @league = League.find(params[:id])
  end

  def index
    @team = Team.find(params[:team_id])
    # @leagues = League.all
    @leagues = League.includes(team_entries: :team).where(team_entries: {team: @team})
  end
end

app/views/leagues/index.html.erb
<div class="retrieve">
  <%#= link_to "Retrieve Leagues", retrieve_team_path(@team), id: "call-to-action" %>
  <%= form_for(@team, url: retrieve_team_path(@team)) do |f| %>
    <div class="form-actions" id="">
      <%= f.submit "Retrieve Leagues", class: 'btn btn-outline-light retrieval', id: 'call-to-action' %>
    </div>
  <% end %>
</div>

<ul class="leagues-list">
  <% @leagues.each do |league| %>
    <li><%= link_to league.name, league_path(league) %></li>
  <% end %>
</ul>

app/views/leagues/show.html.erb
<h1>Leagues#show</h1>
<p>Find me in app/views/leagues/show.html.erb</p>