config/routes.rb
Rails.application.routes.draw do
  get 'leagues/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/about', to: 'pages#about'
  #Routes for user
  resources :users, only: [:show, :edit, :update]

  #Routes for the team
  resources :teams, only: [:show, :new, :create] do
    resources :leagues, only: [:index]
    member do
      get 'finalize', as: :finalize
      patch 'switch', as: :switch
      patch 'retrieve', as: :retrieve
    end
  end

  #Route for transferring player
  resources :players, only: [:edit, :update] do
    get 'modal', to: "players#footballer", as: :modal
  end

  #Routes for footballers
  resources :footballers, only: [:index, :show] do
    get 'modal', to: "teams#footballer", as: :modal
  end

  #Routes for fixtures
  resources :fixtures, only: [:index, :show]

  #Routes for leagues
  resources :leagues, only: [:show]

  # Routes for sidekiq
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_countdown.html.erb
  <% gameweek_info = next_gameweek %>
  <div id="deadline" data-turbolinks-permanent>
    <div id="deadline-countdown" class="text-center pt-3 pr-2" data-gameweek="<%= gameweek_info[0] %>" data-gameweek2="<%= gameweek_info[1] %>"></div>
    <div class="text-center pt-2 pr-2">UNTIL NEXT DEADLINE</div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <%= link_to about_path do %>
      <i class="fas fa-question-circle"></i>
    <% end %>
    <a href="https://github.com/b-skingsley/expectedfpl" target="_blank"><i class="fab fa-github-square"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="nav-left">
    <% unless action_name == 'home' %>
      <%= link_to root_path do %>
        <%= image_tag "logo.png", alt: 'expected fpl logo', id: 'nav-logo' %>
      <% end %>
    <% end %>
  </div>

  <!--   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> -->
  <div class="nav-right">
    <% unless user_signed_in? %>
      <%= link_to "Login", new_user_session_path, class: "nav-link", id: "nav-call-to-action" %>
    <% end %>
    <div class="navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-bars"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <% if current_user.teams.present? %>
                <%= link_to "Team", team_path(current_user.teams.first), class: "dropdown-item" %>
              <% else %>
                <%= link_to "Create Team", new_team_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Fixtures", fixtures_path(status: "current", search: { query: params.dig(:search, :query) }), class: "dropdown-item" %>
              <%= link_to "Player Directory", footballers_path, class: "dropdown-item" %>
              <a href="https://fantasy.premierleague.com/" class="dropdown-item" target="_blank">Premier League</a>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-bars"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to 'Sign-up', new_user_registration_path, class: "dropdown-item" %>
              <% if guest_user.teams.present? %>
                <%= link_to "Team", team_path(guest_user.teams.last), class: "dropdown-item" %>
              <% else %>
                <%= link_to "Create Team", new_team_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Fixtures", fixtures_path, class: "dropdown-item" %>
              <%= link_to "Player Stats", footballers_path, class: "dropdown-item" %>
              <%= link_to "Take a Tour", new_team_path, class: "dropdown-item" %>
              <a href="https://fantasy.premierleague.com/" class="dropdown-item" target="_blank">Premier League</a>
            </div>
          </li>
        <% end %>
        </ul>
    </div>
  </div>
</div>