config/routes.rb
Rails.application.routes.draw do
  get 'leagues/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/about', to: 'pages#about'
  #Routes for user
  resources :users, only: [:show, :edit, :update]

  #Routes for the team
  resources :teams, only: [:show, :new, :create] do
    resources :leagues, only: [:index]
    member do
      get 'finalize', as: :finalize
      patch 'switch', as: :switch
      patch 'retrieve', as: :retrieve
    end
  end

  #Route for transferring player
  resources :players, only: [:edit, :update] do
    get 'modal', to: "players#footballer", as: :modal
  end

  #Routes for footballers
  resources :footballers, only: [:index, :show] do
    get 'modal', to: "teams#footballer", as: :modal
  end

  #Routes for fixtures
  resources :fixtures, only: [:index, :show]

  #Routes for leagues
  resources :leagues, only: [:show]

  # Routes for sidekiq
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  belongs_to :footballer
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # This is the functionality for transferring a player in your team
  def edit
    @player = Player.find(params[:id])
    @team = @player.team
    # Retrieve the footballers already on the team
    @teamplayers = @team.players.map(&:footballer)
    # Save a collection of footballers that play in the same position as the player to be transferred and that aren't already in the team
    @collection = Footballer.where(position: @player.footballer.position).where.not(id: @team.players.pluck(:footballer_id))
    # save the clubs of footballers in the collection
    @clubs = Club.where(id: @collection.pluck(:club_id))

    # price (float) instance variables for use in the view (prices received from API are in integer form such as 112 for £11.2)
    # first a query to reorder the applicable players by price to ascertain max/mins depending on position
    players_by_price = @collection.reorder('price DESC')

    @max_p = (players_by_price.first.price) / 10.0
    @min_p = (players_by_price.last.price) / 10.0

    # Available Budget based on team value and leftover budget from api
    @total_budget = @team.budget + @team.team_value
    @team_value = helpers.price_sum(@team)
    @player_price = @player.footballer.price
    # Define available budget for this transfer taking into account price of player we're transferring out
    @available_budget = @total_budget - @team_value + @player_price

    if params[:query].present?
      @collection = @collection.search_by_first_and_last_name(params[:query])
    elsif params[:filter_by_club].present? || params[:filter_by_max_price].present?
      club_id = @clubs.find_by(name: params[:filter_by_club]).id if params[:filter_by_club].present?
      max_p = (params[:filter_by_max_price].to_f * 10).to_i
      if params[:filter_by_club].present? && params[:filter_by_max_price].present?
        @collection = @collection.where(club_id: club_id).where("price <= ?", max_p)
      elsif params[:filter_by_club].present?
        @collection = @collection.where(club_id: club_id)
      else
        @collection = @collection.where("price <= ?", max_p)
      end
    end
  end

  # Saving the player switch to our db once transfer is confirmed
  def update
    @player = Player.find(params[:id])
    @team = @player.team

    # Find gameweek to save transfer
    @gw = helpers.next_gameweek_no
    player_in = Footballer.find(params[:in])

    # save record of the transfer
    @transfer = Transfer.new(team: @team, player_in: player_in, player_out: @player.footballer, gw: @gw)
    @transfer.save

    # Update the footballer of the player in the team. This way the player maintains the same starter and bench pos status as the player they're replacing
    if @player.update(footballer: Footballer.find(params[:in]))
      redirect_to team_path(@team), notice: "#{player_in.web_name} succesfully transferred in"
    else
      render :edit
    end
  end
end

app/views/players/_footballer_filter_form.html.erb
<% clubs = @clubs.map { |club| club.name } %>

<%= form_tag edit_player_path(@player), class: "form-inline", method: :get do %>
  <div class="col">
    <%= text_field_tag :query,
      params[:query],
      class: "form-control form-control-sm mb-2",
      placeholder: "Search by Name..."
    %>
  </div>
  <div class="col">
    <%= select_tag :filter_by_club, options_for_select(clubs, params[:filter_by_club]),
      include_blank: 'All Clubs',
      class: "form-control form-control-sm mb-2"
    %>
  </div>
  <div class="col">
    <%= label_tag :filter_by_max_price, 'Max Price', class: 'm-0' %>
    <p id="max-price-value" class="m-0 text-center"></p>
    <%= range_field_tag :filter_by_max_price,
      params[:filter_by_max_price].present? ? params[:filter_by_max_price] : @max_p,
      min: @min_p,
      max: @max_p,
      step: 0.1,
      class: "form-control form-control-sm mb-2"
    %>
    <p class="text-center">(Available Budget: <%= fplprice(@available_budget) %>)</p>
  </div>
  <div class="row m-3 justify-content-between">
    <%= submit_tag "Go", class: "btn btn-success btn-sm mx-2" %>
    <%= link_to "Reset", edit_player_path(@player), class: "btn btn-primary btn-sm mx-2", data: { turbolinks: false } %>
  </div>
<% end %>

app/views/players/_modal.html.erb
<% photo = @footballer.photo.gsub(".jpg", "") %>
<% color = Club.find(@footballer.club_id).short_name %>


<div class="container">

  <div class="container d-flex player-header px-0 align-items-end <%= color %> ">
    <div class="container">
        <image src="https://resources.premierleague.com/premierleague/photos/players/110x140/p<%= photo %>.png" alt="">
    </div>
    <div class="w-75" style="text-align: right;">
        <div id="icons-container">
          <% unless attributes_list(@footballer).empty? %>
            <% attributes_list(@footballer).each do |attribute| %>
              <div id="player-show-icons" class="p-2"><i class="<%= attribute %>"></i></div>
            <% end %>
          <% end %>
        </div>

        <div class="text-light text-right p-3">
            <h5><strong><%= @footballer.full_name %></strong></h5>
        </div>
    </div>
  </div>


  <div class="news-reel px-3">
    <span id="typed" data-news="<%= @footballer.news.present? ? @footballer.news : 'No player news to show...' %>" data-fixture="<%= next_fixture(@footballer) %>"></span>
  </div>
  <div class="d-flex bg-light">
    <div class="p-3">
      <div class="d-flex align-items-end">
        <div class="align-self-end">
          <p>Chance of playing next game:</p>
        </div>
        <div class="align-self-end px-3 align-text-bottom">
         <p><%= @footballer.chance_of_playing_this_round %> %</p>
        </div>
      </div>
      <div>
        <progress id="file" max="100" value="<%= @footballer.chance_of_playing_this_round %>"></progress>
      </div>
      <div class="card mt-2">
        <ul class="list-group list-group-flush">
          <li class="list-group-item py-1"><strong>Player Stats:</strong></li>
          <li class="list-group-item border-0">
            <% if @footballer.position == "MID" %>
              <p>Midfielder</p>
            <% elsif @footballer.position == "DEF" %>
              <p>Defender</p>
            <% elsif @footballer.position == "GK" %>
              <p>Goalkeeper</p>
            <% else @footballer.position == "FWD" %>
              <p>Forward</p>
            <% end %>
          </li>
          <li class="list-group-item border-0"><h3>£<%= @footballer.price / 10.to_f %></h3></li>
          <li class="list-group-item border-0"><strong><%= @footballer.minutes %></strong> minutes played ⌚</li>
          <li class="list-group-item border-0"><%= @footballer.minutes.zero? ? "No appearances this season" : "Averages #{((@footballer.bps / @footballer.minutes.to_f) * 90).round(2)}"%> bps per game</li>
          <li class="list-group-item border-0">
              <% if %w(GK DEF).include?(@footballer.position) %>
                  <p><%= @footballer.clean_sheets %> clean sheets</p>
              <% else %>
                  <p><h3>⚽ <strong><%= @footballer.goals %></strong></h3>...goals this season</p>
              <% end %>
          </li>
        </ul>
      </div>
    </div>
    <div class="flex-grow-1 pt-4 justify-content-center align-items-end">
      <div id="graph-container" class="bg-light p-4">

      </div>
      <table class="table table-dark" style="width: 98%">
        <thead>
          <tr>
            <th colspan="4">Next 5 fixtures for <%= @footballer.full_name %></th>
          </tr>
        </thead>
        <tbody>
        <% next_fixtures(@footballer, 5).each do |f| %>
          <tr>
            <th scope="row"><%= f[:kickoff].strftime("%d/%m %h:%m") %></th>
            <td><%= image_tag("shirts/#{f[:shirt]}.png", size: "32x22")  %></td>
            <td><%= f[:opponent_long] %></td>
            <td><% f[:home_or_away] %></td>
          </tr>
        <% end %>
          <tfoot>
            <tr>
            <td style="text-align:right" colspan="4"><%= link_to "View player's full fixture list", fixtures_path(status: "future", search: { query: params[:id] }) %><i class="fas fa-arrow-right pl-3"></i></td>
          </tfoot>
        </tbody>
      </table>
    </div>
  </div>
</div>

<% content_for :chartkick do %>
  <%= javascript_pack_tag 'chartkick' %>
<% end %>

app/views/players/edit.html.erb
<div class="container background-transparent">
  <h2 class="pt-4">Transfer Out - <%= @player.footballer.first_name %> <%= @player.footballer.last_name %></h2>
  <%= link_to "Back to Team", team_path(@team) %>
  <div class="row m-3 justify-content-center align-items-center">
    <div >
      <%= render "footballer_filter_form" %>
    </div>
  </div>
  <div class="container">
    <p id="footballer-count"></p>
    <div class="row justify-content-between filters-icon-row align-items-center">
      <div class="col"></div>
      <div class="col">
        <% if params[:filter_by_position].present? %>
          <p class="filter-feedback"><i class="fas fa-filter"></i> <%= params[:filter_by_position] %></p>
        <% end %>
      </div>
      <div class="col">
        <% if params[:filter_by_club].present? %>
          <p class="filter-feedback"><i class="fas fa-filter"></i> <%= params[:filter_by_club] %></p>
        <% end %>
      </div>
      <div class="col"></div>
      <div class="col">
        <% if params[:filter_by_max_price].present? && params[:filter_by_max_price].to_f < @max_p %>
          <p class="filter-feedback"><i class="fas fa-filter"></i> Max: <%= params[:filter_by_max_price] %></p>
        <% end %>
      </div>
      <div class="col"></div>
    </div>



    <div class="row justify-content-between sort-icon-row align-items-center">
      <div class="col-3"></div>
      <div class="col-1"></div>
      <div class="col-2"></div>
      <div class="col-2"></div>
      <div class="col-2">
        <p id="sort-price-up" class="sort-icon text-center hidden"><i class="fas fa-sort-up"></i></p>
      </div>
      <div class="col-2">
        <p id="sort-points-up" class="sort-icon text-center hidden"><i class="fas fa-sort-up"></i></p>
      </div>
    </div>
    <div class="row justify-content-between table-header align-items-center">
      <div class="col-3">
        <p>Name</p>
      </div>
      <div class="col-1">
      </div>
      <div class="col-2">
        <p>Club</p>
      </div>
      <div class="col-2">
        <p>Availability</p>
      </div>
      <div class="col-2">
        <p>Price</p>
      </div>
      <div class="col-2">
        <p>Total Points</p>
      </div>
    </div>
    <div class="row justify-content-between sort-icon-row align-items-center">
      <div class="col"></div>
      <div class="col"></div>
      <div class="col"></div>
      <div class="col"></div>
      <div class="col">
        <p id="sort-price-down" class="sort-icon text-center hidden"><i class="fas fa-sort-down"></i></p>
      </div>
      <div class="col">
        <p id="sort-points-down" class="sort-icon activated text-center"><i class="fas fa-sort-down"></i></p>
      </div>
    </div>

    <!-- This is the player being transferred out -->
    <div id="transfer-out" class="row justify-content-between table-row align-items-center" data-position="<%= @player.footballer.position %>">
      <div class="col-3" ><p><%= @player.footballer.web_name %></p></div>
      <div class="col-1" ><i class="fas fa-user-minus"></i></div>
      <div class="col-2" ><p><%= @player.footballer.club.short_name %></p></div>
      <div class="col-2" ><p><%= chances_formatter(@player.footballer.chance_of_playing_next_round) %></p></div>
      <div class="col-2" ><p><%= fplprice(@player.footballer.price) %></p></div>
      <div class="col-2" ><p><%= @player.footballer.total_points %> <%= form_formatter(@player.footballer.form.to_f) %></p></div>
    </div>
  </div>
  <!-- These are the footballers in same position as transferred out player, not already in the team -->
  <div class="container table-body" style="overflow:scroll; max-height:50vh;">
    <% unless @collection.present? %>
    <div class="text-center">
      <div class="m-4"><h3>⚽️😐 No Players Matching Your Filter Criteria 😐⚽️</h3></div>
      <div><%= link_to "Reset Filters", footballers_path, class: "btn btn-secondary btn-sm", data: { turbolinks: false } %></div>
    </div>
    <% end %>
    <% @collection.each do |footballer| %>
    <div class="row justify-content-between table-row row-hover-highlight align-items-center footballer" data-id="<%= footballer.id %>" data-webName="<%= footballer.web_name %>" data-fullName="<%= "#{footballer.first_name} #{footballer.last_name}" %>" data-position="<%= footballer.position %>" data-club="<%= footballer.club.name %>" data-chances="<%= footballer.chance_of_playing_next_round %>" data-news="<%= footballer.news %>" data-price="<%= fplprice(footballer.price) %>" data-points="<%= footballer.total_points %>" data-form="<%= footballer.form.to_f %>">
      <div class="col-3" ><p><%= footballer.web_name %></p></div>
      <div class="col-1" ><%= link_to player_path(in: footballer.id, out: @player.footballer.id), method: :patch, data: { confirm: "Would you like to transfer in #{footballer.web_name} for #{@player.footballer.web_name}?" } do %>
          <i class="fas fa-user-plus"></i>
        <% end %>
      </div>
      <div class="col-2" ><p><%= footballer.club.short_name %></p></div>
      <div class="col-2" ><p><%= chances_formatter(footballer.chance_of_playing_next_round) %></p></div>
      <div class="col-2" ><p><%= fplprice(footballer.price) %></p></div>
      <div class="col-2" ><p><%= footballer.total_points %> <%= form_formatter(footballer.form.to_f) %></p></div>

    </div>
      <div id="expanded-content-<%= footballer.id %>" class="footballer-info mx-auto hidden">
        <div class="expanded-left">
          <div class="expanded-name">
            <h4><%= "#{footballer.first_name} #{footballer.last_name}" %></h4>
          </div>
          <div class="news-div">
            <p class="news"><%= footballer.news if footballer.news.length > 0 %></p>
          </div>
          <p><i class="fas fa-tshirt"></i> <%= footballer.club.name %></p>
          <p><i class="fas fa-pound-sign"></i> <%= fplprice(footballer.price) %>   |   <i class="fas fa-fire" data-toggle="tooltip" data-placement="top" title="Average points per game for last 5"></i> <%= footballer.form.to_f %>   |   <i class="fas fa-chart-bar" data-toggle="tooltip" data-placement="top" title="Total Points"></i> <%= footballer.total_points %></p>
          <p><i class="far fa-futbol" data-toggle="tooltip" data-placement="top" title="Goals this season"></i> <%= footballer.goals %>   |   <i class="fas fa-hands-helping" data-toggle="tooltip" data-placement="top" title="Assists this season"></i> <%= footballer.assists %></p>
          <button type="button" id="footballer-details-<%= footballer.id %>" class="call-to-action" data-toggle="modal" data-target="#exampleModalLong">More Info</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      </div>
    </div>
  </div>
</div>