config/routes.rb
Rails.application.routes.draw do
  get 'leagues/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/about', to: 'pages#about'
  #Routes for user
  resources :users, only: [:show, :edit, :update]

  #Routes for the team
  resources :teams, only: [:show, :new, :create] do
    resources :leagues, only: [:index]
    member do
      get 'finalize', as: :finalize
      patch 'switch', as: :switch
      patch 'retrieve', as: :retrieve
    end
  end

  #Route for transferring player
  resources :players, only: [:edit, :update] do
    get 'modal', to: "players#footballer", as: :modal
  end

  #Routes for footballers
  resources :footballers, only: [:index, :show] do
    get 'modal', to: "teams#footballer", as: :modal
  end

  #Routes for fixtures
  resources :fixtures, only: [:index, :show]

  #Routes for leagues
  resources :leagues, only: [:show]

  # Routes for sidekiq
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/footballer.rb
class Footballer < ApplicationRecord
  belongs_to :club
  has_many :players
  has_many :odds
  has_many :transfers

  default_scope { order(total_points: :desc) }

  validates :first_name, :last_name, :position, :price, :fplid, presence: true
  validates :position, inclusion: { in: %w(GK DEF MID FWD UNKNOWN gk def mid fwd) }
  validates :price, numericality: { greater_than: 30, less_than: 150 }
  validates :fplid, uniqueness: true

  scope :fwds, -> { where(position: "FWD") }
  scope :mids, -> { where(position: "MID") }
  scope :defs, -> { where(position: "DEF") }
  scope :gks, -> { where(position: "GK") }
  scope :unknowns, -> { where(position: "UNKNOWN") }

  include PgSearch::Model
  pg_search_scope :search_by_first_and_last_name,
    against: [ :first_name, :last_name ],
    using: {
      tsearch: { prefix: true }
    }

  include AlgoliaSearch
  algoliasearch do
    attributes :first_name, :last_name
    attribute :full_name
    searchableAttributes ['unordered(last_name)', 'unordered(first_name)']
  end

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/footballers_controller.rb
class FootballersController < ApplicationController
  def index
    @footballers = Footballer.all
    players_by_price = @footballers.reorder('price DESC')

    # price (float) instance variables for use in the view

    @max_p = (players_by_price.first.price) / 10.0
    @min_p = (players_by_price.last.price) / 10.0

    @clubs = Club.all

    if params[:query].present?
      @footballers = @footballers.search_by_first_and_last_name(params[:query])
    elsif params[:filter_by_position].present? || params[:filter_by_club].present? || params[:filter_by_max_price].present?
      position = params[:filter_by_position]
      club_id = @clubs.find_by(name: params[:filter_by_club]).id if params[:filter_by_club].present?
      max_p = (params[:filter_by_max_price].to_f * 10).to_i
      if params[:filter_by_position].present? && params[:filter_by_club].present? && params[:filter_by_max_price].present?
        @footballers = @footballers.where(position: position, club_id: club_id).where("price <= ?", max_p)
      elsif params[:filter_by_position].present? && params[:filter_by_club].present?
        @footballers = @footballers.where(position: position, club_id: club_id)
      elsif params[:filter_by_position].present? && params[:filter_by_max_price].present?
        @footballers = @footballers.where(position: position).where("price <= ?", max_p)
      elsif params[:filter_by_club].present? && params[:filter_by_max_price].present?
        @footballers = @footballers.where(club_id: club_id).where("price <= ?", max_p)
      elsif params[:filter_by_position].present?
        @footballers = @footballers.where(position: position)
      elsif params[:filter_by_club].present?
        @footballers = @footballers.where(club_id: club_id)
      else
        @footballers = @footballers.where("price <= ?", max_p)
      end
    end

  end

  def show
    @footballer = Footballer.find(params[:id])
    @next_gw = helpers.next_gameweek_no
    @fixtures = Fixture.where(gameweek: (@next_gw..(@next_gw + 6))).order(:kickoff)
  end
end

app/helpers/footballer_helper.rb
require 'open-uri'
require 'json'

module FootballerHelper
  # Calling the API
  def completed_games_data
    fixtures_url = 'https://fantasy.premierleague.com/api/fixtures/'
    request = URI.open(fixtures_url).read
    data = JSON.parse(request)
    data.select { |f| f["finished"] == true }
  end

  def bps_per_game(player_fpl_id)
    finished_games = completed_games_data
    most_recent_gameweek = finished_games.last["event"]

    # Filter only relevant data (bps)
    finished_games.map! do |game|
        (game["stats"][9]["a"] + game["stats"][9]["h"])
    end

    counter = most_recent_gameweek
    arr = [] 
    while counter > 0 do   
      player_points_hash = Hash.new(0)
      player_points_hash[player_fpl_id] = 0

      gameweek_allocated_points = finished_games[most_recent_gameweek - counter].to_a.flatten
      gameweek_allocated_points.map! do |game|
          game.values
      end

      player_gameweek_points = gameweek_allocated_points.select { |point_allocation| point_allocation[1] == player_fpl_id }
      player_gameweek_points.flatten ? arr << player_gameweek_points.flatten[0] : arr << [0]
      counter -= 1
    end

    arr.map! { |i| i.nil? ? i = 0 : i }

    points_by_game = Hash.new
    arr.each_with_index do |element, index|
      points_by_game[index] = element
    end
    points_by_game
  end

  def player_historical_data(fplid)
    url = 'https://fantasy.premierleague.com/api/element-summary/' + "#{fplid.to_s}/"
    request = URI.open(url).read
    data = JSON.parse(request)
    data["history"].flatten
  end

  # player_historical_data(400)
  # values = player_historical_data(400).map { |hash| hash.select { |attribute| attribute["bps"] } }
  # just_values = values.map!{ |key, item|item.values }.flatten
  # p just_values

  def historical_value(fplid)
    values = player_historical_data(fplid).map { |hash| hash.select { |attribute| attribute["value"] } }
    arr = []
    values.each_with_index { |hash, index| arr << { (index + 1) => hash["value"] } }
    arr
  end

  def popularity(fplid)
    ongoing_values = player_historical_data(fplid).map { |hash| hash.select { |attribute| attribute["transfers_balance"] } }
    arr = []
    current = 0
    # array.reduce(0) { |sum, num| sum + num }
    ongoing_values.each_with_index do |hash, index|
      current += hash["transfers_balance"]
      arr << { (index + 1) => current }
    end
    arr.reduce Hash.new, :merge
  end
 

  def bps(fplid)
    values = player_historical_data(fplid).map { |hash| hash.select { |attribute| attribute["bps"] } }
    just_values = values.map!{ |item| item.values }.flatten
    arr = {}
    just_values.each_with_index do |value, index|
      arr[index] = value
    end
    arr
  end


    # Method for calculating moving average
  def wma_hash(hash, maws = MAWS)
    # hash = hash.reduce Hash.new, :merge
    sum = maws * (maws + 1) / 2

    values = hash.to_a.reverse # recent averages are the most important ones
    values_size = values.size

    values.each_with_index do |kv, pos|
      weighted_sum = 0

      0.upto(maws - 1) do |i|
        weighted_sum += values[i + pos].last * (i + 1)
      end

      hash[values[pos+1].first] = weighted_sum.to_f / sum

      return hash if pos + maws == values_size
    end
  end
end

app/views/footballers/_footballer_filter_form.html.erb
<% clubs = @clubs.map { |club| club.name } %>

<%= form_tag footballers_path, class: "form-inline", method: :get do %>
  <div class="col">
    <%= text_field_tag :query,
      params[:query],
      class: "form-control form-control-sm mb-2",
      placeholder: "Search by Name..."
    %>
  </div>
  <div class="col">
    <%= select_tag :filter_by_position, options_for_select(%w[GK DEF MID FWD], params[:filter_by_position]),
      include_blank: 'All Positions',
      class: "form-control form-control-sm mb-2"
    %>
  </div>
  <div class="col">
    <%= select_tag :filter_by_club, options_for_select(clubs, params[:filter_by_club]),
      include_blank: 'All Clubs',
      class: "form-control form-control-sm mb-2"
    %>
  </div>
  <div class="col">
    <%= label_tag :filter_by_max_price, 'Max Price', class: 'm-0' %>

    <%= range_field_tag :filter_by_max_price,
      params[:filter_by_max_price].present? ? params[:filter_by_max_price] : @max_p,
      min: @min_p,
      max: @max_p,
      step: 0.1,
      class: "form-control form-control-sm mb-2"
    %>
    <p id="max-price-value" class="m-0 text-center"></p>
  </div>
  <div class="row m-3 justify-content-between">
    <%= submit_tag "Go", class: "btn btn-success btn-sm mx-2" %>
    <%= link_to "Reset", footballers_path, class: "btn btn-primary btn-sm mx-2", data: { turbolinks: false } %>
  </div>
<% end %>

app/views/footballers/index.html.erb
<div class="container background-transparent">
  <h2 class="pt-4">Player Directory</h2>
  <div class="row m-3 justify-content-center align-items-center">
    <div>
      <%= render "footballer_filter_form" %>
    </div>
  </div>
  <div class="container">
    <p id="footballer-count"></p>
    <div class="row justify-content-between filters-icon-row align-items-center">
      <div class="col"></div>
      <div class="col">
        <% if params[:filter_by_position].present? %>
          <p class="filter-feedback"><i class="fas fa-filter"></i> <%= params[:filter_by_position] %></p>
        <% end %>
      </div>
      <div class="col">
        <% if params[:filter_by_club].present? %>
          <p class="filter-feedback"><i class="fas fa-filter"></i> <%= params[:filter_by_club] %></p>
        <% end %>
      </div>
      <div class="col"></div>
      <div class="col">
        <% if params[:filter_by_max_price].present? && params[:filter_by_max_price].to_f < @max_p %>
          <p class="filter-feedback"><i class="fas fa-filter"></i> Max: <%= params[:filter_by_max_price] %></p>
        <% end %>
      </div>
      <div class="col"></div>
    </div>

    <div class="row justify-content-between sort-icon-row align-items-center">
      <div class="col"></div>
      <div class="col"></div>
      <div class="col"></div>
      <div class="col"></div>
      <div class="col">
        <p id="sort-price-up" class="sort-icon text-center hidden"><i class="fas fa-sort-up"></i></p>
      </div>
      <div class="col">
        <p id="sort-points-up" class="sort-icon text-center hidden"><i class="fas fa-sort-up"></i></p>
      </div>
    </div>
    <div class="row justify-content-between table-header align-items-center">
      <div class="col">
        <p>Name</p>
      </div>
      <div class="col">
        <p>Position</p>
      </div>
      <div class="col">
        <p>Club</p>
      </div>
      <div class="col">
        <p>Availability</p>
      </div>
      <div class="col">
        <p>Price</p>
      </div>
      <div class="col">
        <p>Total Points</p>
      </div>
    </div>
    <div class="row justify-content-between sort-icon-row align-items-center">
      <div class="col"></div>
      <div class="col"></div>
      <div class="col"></div>
      <div class="col"></div>
      <div class="col">
        <p id="sort-price-down" class="sort-icon text-center hidden"><i class="fas fa-sort-down"></i></p>
      </div>
      <div class="col">
        <p id="sort-points-down" class="sort-icon activated text-center"><i class="fas fa-sort-down"></i></p>
      </div>
    </div>
  </div>
  <div class="container table-body" style="overflow:scroll; max-height:50vh;">
    <% unless @footballers.present? %>
    <div class="text-center">
      <div class="m-4"><h3>⚽️😐 No Players Matching Your Filter Criteria 😐⚽️</h3></div>
      <div><%= link_to "Reset Filters", footballers_path, class: "btn btn-secondary btn-sm", data: { turbolinks: false } %></div>
    </div>
    <% end %>
    <% @footballers.each do |footballer| %>
    <div class="footballer" data-id="<%= footballer.id %>" data-webName="<%= footballer.web_name %>" data-fullName="<%= "#{footballer.first_name} #{footballer.last_name}" %>" data-position="<%= footballer.position %>" data-club="<%= footballer.club.name %>" data-chances="<%= footballer.chance_of_playing_next_round %>" data-news="<%= footballer.news %>" data-price="<%= fplprice(footballer.price) %>" data-points="<%= footballer.total_points %>" data-form="<%= footballer.form.to_f %>">
      <div class="row justify-content-between table-row row-hover-highlight align-items-center">
        <div class="col" ><p><%= footballer.web_name %></p></div>
        <div class="col" ><p><%= footballer.position %></p></div>
        <div class="col" ><p><%= footballer.club.name %></p></div>
        <div class="col" ><p><%= chances_formatter(footballer.chance_of_playing_next_round) %></p></div>
        <div class="col" ><p><%= fplprice(footballer.price) %></p></div>
        <div class="col" ><p><%= footballer.total_points %> <%= form_formatter(footballer.form.to_f) %></p></div>
      </div>
      <div  class="d-flex flex-column footballer-info">
        <div id="expanded-content-<%= footballer.id %>" class="hidden text-center pt-3 footballer-details">
          <p><%= footballer.full_name %>  |    Averaged <%= footballer.form %> points per-game, over last 5 games<span class="news"><%= footballer.news %></span></p>
          <%# <button class="btn btn-primary">See more info</button> %>
          <%= link_to footballer_path(footballer) do %>
            <button type="button" class="see-footballer mb-2 hidden">See player</button>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/footballers/show.html.erb
<% content_for :chartkick do %>
  <%= javascript_pack_tag 'chartkick' %>
<% end %>



<% photo = @footballer.photo.gsub(".jpg", "") %>
<% color = Club.find(@footballer.club_id).short_name %>


<div class="container">

  <div class="container d-flex player-header px-0 align-items-end <%= color %> ">
    <div class="container d-flex flex-column align-items-between h-100  ">
      <div class="flex-grow-1 mb-auto align-item-end"><i class="fas fa-arrow-left pr-2"></i><%= link_to "Back to all players", footballers_path, id: "back-to-footballers-index" %></div>
      <image src="https://resources.premierleague.com/premierleague/photos/players/110x140/p<%= photo %>.png" alt="" width="220px" height="280px">
    </div>
    <div class="w-75" style="text-align: right;">
        <div id="icons-container">
          <% unless attributes_list(@footballer).empty? %>
            <% attributes_list(@footballer).each do |attribute| %>
              <div id="player-show-icons" class="finalize-link disabled p-2"><i class="<%= attribute.values.join("") %>" data-toggle="tooltip" data-placement="top" title="<%= attribute.keys[0] %>"></i></div>
            <% end %>
          <% end %>
        </div>

        <div class="text-light text-right p-3">
            <h5><strong><%= @footballer.full_name %></strong></h5>
        </div>
    </div>
  </div>


  <div class="news-reel px-3">
    <span id="typed" data-news="<%= @footballer.news.present? ? @footballer.news : 'No player news to show...' %>" data-fixture="<%= next_fixture(@footballer) %>"></span>
  </div>
  <div class="d-flex bg-light justify-content-between">
    <div class="p-3 flex-grow-1">
      <div class="d-flex align-items-end">
        <div class="align-self-end">
          <p>Chance of playing next game:</p>
        </div>
        <div class="align-self-end px-3 align-text-bottom">
         <p><%= @footballer.chance_of_playing_this_round %> %</p>
        </div>
      </div>
      <div>
        <progress id="file" max="100" value="<%= @footballer.chance_of_playing_this_round %>"></progress>
      </div>
      <div class="card mt-2">
        <ul class="list-group list-group-flush">
          <li class="list-group-item py-1"><strong>Player Stats:</strong></li>
          <li class="list-group-item border-0">
            <% if @footballer.position == "MID" %>
              <p>Midfielder</p>
            <% elsif @footballer.position == "DEF" %>
              <p>Defender</p>
            <% elsif @footballer.position == "GK" %>
              <p>Goalkeeper</p>
            <% else @footballer.position == "FWD" %>
              <p>Forward</p>
            <% end %>
          </li>
          <li class="list-group-item border-0"><h3>£<%= @footballer.price / 10.to_f %></h3></li>
          <li class="list-group-item border-0"><strong><%= @footballer.minutes %></strong> minutes played ⌚</li>
          <li class="list-group-item border-0"><%= @footballer.minutes.zero? ? "No appearances this season" : "Averages #{((@footballer.bps / @footballer.minutes.to_f) * 90).round(2)}"%> bps per game</li>
          <li class="list-group-item border-0">
              <% if %w(GK DEF).include?(@footballer.position) %>
                  <p><%= @footballer.clean_sheets %> clean sheets</p>
              <% else %>
                  <p><h3>⚽ <strong><%= @footballer.goals %></strong></h3>...goals this season</p>
              <% end %>
          </li>
        </ul>
      </div>
    </div>
    <div class="p-3 justify-content-center align-items-end">

      <div id="graph-container" class="bg-light p-4">
        <%= line_chart wma_hash(bps(@footballer.fplid), maws = 3), id: "bps-chart", width: "700px", height: "150px", xtitle: "Game", ytitle: "BPS", precision: 3 %>
      </div>

      <table class="table table-dark">
        <thead>
          <tr>
            <th colspan="5">Next 5 fixtures for <%= @footballer.full_name %></th>
          </tr>
        </thead>
        <tbody>
        <% next_fixtures(@footballer, 5).each do |f| %>
          <tr>
            <th scope="row"><%= f[:kickoff].strftime("%a %d/%m - %H:%M") %></th>
            <td><%= image_tag("shirts/#{f[:shirt]}.png", size: "32x22")  %></td>
            <td><%= f[:opponent_long] %></td>
            <td><%= f[:home_or_away] %></td>
            <td style="width: 120px;"><div id="difficulty-bar" data-difficulty="<%= f[:difficulty] * 20 %>" data-toggle="tooltip" data-placement="top" title="Difficulty rating of this fixtue for <%= @footballer.club.short_name %>: <%= f[:difficulty] * 20 %>/100"></div></td>
          </tr>
        <% end %>
          <tfoot>
            <tr>
            <td style="text-align:right" colspan="5">View player's full fixture list<i class="fas fa-arrow-right pl-3"></i></td>
          </tfoot>
        </tbody>
      </table>
    </div>
  </div>
</div>